In [1]:
!pip install selenium webdriver-manager

Collecting selenium
  Obtaining dependency information for selenium from https://files.pythonhosted.org/packages/74/9e/642a355e43a4ebf68bc4f00dd4ab264f635079c5dc7ed6d9991a0c2be3d7/selenium-4.36.0-py3-none-any.whl.metadata
  Downloading selenium-4.36.0-py3-none-any.whl.metadata (7.5 kB)
Collecting webdriver-manager
  Obtaining dependency information for webdriver-manager from https://files.pythonhosted.org/packages/b5/b5/3bd0b038d80950ec13e6a2c8d03ed8354867dc60064b172f2f4ffac8afbe/webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting urllib3[socks]<3.0,>=2.5.0 (from selenium)
  Obtaining dependency information for urllib3[socks]<3.0,>=2.5.0 from https://files.pythonhosted.org/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl.metadata
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting trio<1.0,>=0.30.0 (from selenium)
  Obtaining dependency information for trio<1.0,>=0.30.0 from https://files.pythonhosted.org/packages/31/5b/94237a3485620dbff9741df02ff6d8acaa5fdec67d81ab3f62e4d8511bf7/trio-0.31.0-py3-none-any.whl.metadata
  Downloading trio-0.31.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Obtaining dependency information for trio-websocket<1.0,>=0.12.2 from https://files.pythonhosted.org/packages/c7/19/eb640a397bba49ba49ef9dbe2e7e5c04202ba045b6ce2ec36e9cadc51e04/trio_websocket-0.12.2-py3-none-any.whl.metadata
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting certifi>=2025.6.15 (from selenium)
  Obtaining dependency information for certifi>=2025.6.15 from https://files.pythonhosted.org/packages/e4/37/af0d2ef3967ac0d6113837b44a4f0bfe1328c2b9763bd5b1744520e5cfed/certifi-2025.10.5-py3-none-any.whl.metadata
  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)
Collecting typing_extensions<5.0,>=4.14.0 (from selenium)
  Obtaining dependency information for typing_extensions<5.0,>=4.14.0 from https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Obtaining dependency information for websocket-client<2.0,>=1.8.0 from https://files.pythonhosted.org/packages/5a/84/44687a29792a70e111c5c477230a72c4b957d88d16141199bf9acb7537a3/websocket_client-1.8.0-py3-none-any.whl.metadata
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: requests in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from webdriver-manager) (2.31.0)
Requirement already satisfied: python-dotenv in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from webdriver-manager) (23.1)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.30.0->selenium)
  Obtaining dependency information for attrs>=23.2.0 from https://files.pythonhosted.org/packages/3a/2a/7cc015f5b9f5db42b7d48157e23356022889fc354a2813c15934b7cb5c0e/attrs-25.4.0-py3-none-any.whl.metadata
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: sortedcontainers in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from trio<1.0,>=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from trio<1.0,>=0.30.0->selenium) (3.4)
Collecting outcome (from trio<1.0,>=0.30.0->selenium)
  Obtaining dependency information for outcome from https://files.pythonhosted.org/packages/55/8b/5ab7257531a5d830fc8000c476e63c935488d74609b50f9384a643ec0a62/outcome-1.3.0.post0-py2.py3-none-any.whl.metadata
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.30.0->selenium)
  Obtaining dependency information for sniffio>=1.3.0 from https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl.metadata
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Obtaining dependency information for wsproto>=0.14 from https://files.pythonhosted.org/packages/78/58/e860788190eba3bcce367f74d29c4675466ce8dddfba85f7827588416f01/wsproto-1.2.0-py3-none-any.whl.metadata
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/raffaelruppert/anaconda3/lib/python3.11/site-packages (from requests->webdriver-manager) (2.0.4)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Obtaining dependency information for h11<1,>=0.9.0 from https://files.pythonhosted.org/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl.metadata
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading selenium-4.36.0-py3-none-any.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 6.7 MB/s eta 0:00:0000:0100:01
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 3.6 MB/s eta 0:00:00a 0:00:01
Downloading trio-0.31.0-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.7/512.7 kB 5.4 MB/s eta 0:00:0000:0100:01
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 1.2 MB/s eta 0:00:00
Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 1.6 MB/s eta 0:00:00
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 1.9 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.8/129.8 kB 3.0 MB/s eta 0:00:00a 0:00:01
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: websocket-client, urllib3, typing_extensions, sniffio, h11, certifi, attrs, wsproto, outcome, webdriver-manager, trio, trio-websocket, selenium
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 0.58.0
    Uninstalling websocket-client-0.58.0:
      Successfully uninstalled websocket-client-0.58.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2023.7.22
    Uninstalling certifi-2023.7.22:
      Successfully uninstalled certifi-2023.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 22.1.0
    Uninstalling attrs-22.1.0:
      Successfully uninstalled attrs-22.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.29.76 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.5.0 which is incompatible.
Successfully installed attrs-25.4.0 certifi-2025.10.5 h11-0.16.0 outcome-1.3.0.post0 selenium-4.36.0 sniffio-1.3.1 trio-0.31.0 trio-websocket-0.12.2 typing_extensions-4.15.0 urllib3-2.5.0 webdriver-manager-4.0.2 websocket-client-1.8.0 wsproto-1.2.0

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time

print("✅ Selenium & BeautifulSoup importiert.")

✅ Selenium & BeautifulSoup importiert.

In [3]:
# Chrome im Headless-Modus starten (läuft ohne sichtbares Fenster)
options = Options()
options.add_argument("--headless")          
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

# ChromeDriver automatisch herunterladen und starten
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

url = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen"
driver.get(url)

# etwas warten, bis JavaScript alles geladen hat
time.sleep(5)

# kompletten HTML-Inhalt der Seite holen
html = driver.page_source
driver.quit()

print("✅ Seite geladen – HTML-Länge:", len(html))

✅ Seite geladen – HTML-Länge: 283186

In [4]:
soup = BeautifulSoup(html, "html.parser")

# Suche alle Einträge mit class="member-list-item"
entries = soup.select("div.member-list-item")

print(f"Gefundene Organisationseinträge: {len(entries)}")

# Zeige die ersten 5 als Vorschau
for e in entries[:5]:
    name = e.select_one("h2")
    link = e.select_one("a")
    print("→", name.get_text(strip=True) if name else None)
    print("   ", "https://www.paritaet-berlin.de" + link["href"] if link else None)

Gefundene Organisationseinträge: 0

In [5]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

url = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen"
driver.get(url)

# ⏳ Warte bis mindestens ein Element mit class="member-list-item" vorhanden ist
try:
    WebDriverWait(driver, 15).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "div.member-list-item"))
    )
    print("✅ Organisationseinträge gefunden (Seite fertig geladen)")
except:
    print("⚠️ Timeout – keine Organisationen nach 15s gefunden")

html = driver.page_source
driver.quit()

⚠️ Timeout – keine Organisationen nach 15s gefunden

In [6]:
import requests
from bs4 import BeautifulSoup

url = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen?tx_lfmembers_list[offset]=10"
r = requests.get(url)
print("Status:", r.status_code)
print("HTML-Länge:", len(r.text))

soup = BeautifulSoup(r.text, "html.parser")
print(soup.prettify()[:2000])  # nur die ersten 2000 Zeichen anzeigen

Status: 200
HTML-Länge: 289293
<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="de-DE">
 <head>
  <meta charset="utf-8"/>
  <!--
	This website is powered by TYPO3 - inspiring people to share!
	TYPO3 is a free open source Content Management Framework initially created by Kasper Skaarhoj and licensed under GNU/GPL.
	TYPO3 is copyright 1998-2025 of Kasper Skaarhoj. Extensions are copyright of their respective owners.
	Information and contribution at https://typo3.org/
-->
  <title>
   Unsere Mitgliedsorganisationen | Parität Berlin
  </title>
  <meta content="TYPO3 CMS" name="generator">
   <meta content="https://www.paritaet-berlin.de/fileadmin/user_upload/redaktion/Bilder/SocialMedia/facebook_paritaet_berlin_1200_630.jpg" property="og:image"/>
   <meta content="https://www.paritaet-berlin.de/fileadmin/user_upload/redaktion/Bilder/SocialMedia/facebook_paritaet_berlin_1200_630.jpg" property="og:image"/>
   <meta content="website" property="og:type"/>
   <meta content="Parität Berlin" property="og:site_name"/>
   <meta content="https://www.paritaet-berlin.de/fileadmin/_processed_/1/6/csm_twitter_paritaet_berlin_1024_512_9b3188d06c.jpg" name="twitter:image"/>
   <meta content="summary_large_image" name="twitter:card"/>
   <meta content="@ParitaetBerlin" name="twitter:creator"/>
   <meta content="@ParitaetBerlin" name="twitter:site"/>
   <link href="/assets/styles/main.css?1757674701" media="all" rel="stylesheet"/>
   <link href="/assets/styles/form.css?1757674701" media="all" rel="stylesheet"/>
   <link href="/typo3conf/ext/lf_base/Resources/Public/CSS/shame.css?1757674781" media="all" rel="stylesheet"/>
   <script defer="defer" src="/assets/scripts/main.js?1757674698">
   </script>
   <script defer="defer" nomodule="nomodule" src="/assets/scripts/main.es5.js?1757674698">
   </script>
   <meta content="width=device-width, initial-scale=1, user-scalable=yes, viewport-fit=cover" name="viewport"/>
   <meta content="telephone=no" name="format-detection"/>
   <meta content="IE=edge" http-equiv="X-UA-Co

In [7]:
# Wir durchsuchen gezielt den unteren Teil der Seite
from bs4 import BeautifulSoup
import requests

url = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen?tx_lfmembers_list[offset]=10"
r = requests.get(url)
soup = BeautifulSoup(r.text, "html.parser")

# Such mal alle h3-Elemente (oft enthalten sie die Organisationsnamen)
for h3 in soup.find_all("h3")[:10]:
    print(h3.get_text(strip=True))

print("\n--- Ende der Vorschau ---")

Hier finden Sie eine Übersicht aller Mitgliedsorganisationen des Paritätischen Berlin. Einzelne Organisationen finden Sie über die alphabetische Reihenfolge oder über Suchbegriffe.
afro-talents e. V.
ajb gmbh Gemeinnützige Gesellschaft für Jugendberatung und psychosoziale Rehabilitation
AJC GmbH Gemeinnützige Gesellschaft für Jugendberatung und psychosoziale Rehabilitation
Aktion 70 - Jugendhilfe im Verbund e. V.
Aktion Courage e. V. - SOS Rassismus
Aktion für Flüchtlingshilfe e. V.
aktion weitblick - betreutes wohnen - gGmbH
aktion weitblick e. V. (Interessengemeinschaft zur Förderung beeinträchtigter Mitbürger, insbesondere ehemaliger Auszubildender des Berufsbildungswerkes Rotkreuz-Institut in Berlin-Kladow) e. V.
Albatros - Lebensnetz gGmbH

--- Ende der Vorschau ---

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep

BASE_URL = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen"
results = []

# Schleife über alle Seiten (0–810)
for offset in range(0, 820, 10):
    url = f"{BASE_URL}?tx_lfmembers_list[offset]={offset}"
    print(f"🔹 Lade Seite mit Offset={offset} …")

    r = requests.get(url)
    if r.status_code != 200:
        print(f"⚠️ Fehler bei {url}: Status {r.status_code}")
        continue

    soup = BeautifulSoup(r.text, "html.parser")
    orgs = soup.find_all("h3")

    if not orgs:
        print(f"⚠️ Keine Organisationen auf Seite {offset} gefunden")
        continue

    for org in orgs:
        name = org.get_text(strip=True)
        results.append({"Name": name})

    print(f"✅ {len(orgs)} Organisationen gefunden (bisher insgesamt {len(results)})")
    sleep(1)

print(f"\n🎉 Fertig! Insgesamt {len(results)} Organisationen gesammelt.")

# Ergebnisse als DataFrame anzeigen
df = pd.DataFrame(results)
display(df.head(20))  # zeige erste 20 Organisationen
print(f"Gesamtzahl der Organisationen: {len(df)}")

🔹 Lade Seite mit Offset=0 …
✅ 14 Organisationen gefunden (bisher insgesamt 14)
🔹 Lade Seite mit Offset=10 …
✅ 14 Organisationen gefunden (bisher insgesamt 28)
🔹 Lade Seite mit Offset=20 …
✅ 14 Organisationen gefunden (bisher insgesamt 42)
🔹 Lade Seite mit Offset=30 …
✅ 14 Organisationen gefunden (bisher insgesamt 56)
🔹 Lade Seite mit Offset=40 …
✅ 14 Organisationen gefunden (bisher insgesamt 70)
🔹 Lade Seite mit Offset=50 …
✅ 14 Organisationen gefunden (bisher insgesamt 84)
🔹 Lade Seite mit Offset=60 …
✅ 14 Organisationen gefunden (bisher insgesamt 98)
🔹 Lade Seite mit Offset=70 …
✅ 14 Organisationen gefunden (bisher insgesamt 112)
🔹 Lade Seite mit Offset=80 …
✅ 14 Organisationen gefunden (bisher insgesamt 126)
🔹 Lade Seite mit Offset=90 …
✅ 14 Organisationen gefunden (bisher insgesamt 140)
🔹 Lade Seite mit Offset=100 …
✅ 14 Organisationen gefunden (bisher insgesamt 154)
🔹 Lade Seite mit Offset=110 …
✅ 14 Organisationen gefunden (bisher insgesamt 168)
🔹 Lade Seite mit Offset=120 …
✅ 14 Organisationen gefunden (bisher insgesamt 182)
🔹 Lade Seite mit Offset=130 …
✅ 14 Organisationen gefunden (bisher insgesamt 196)
🔹 Lade Seite mit Offset=140 …
✅ 14 Organisationen gefunden (bisher insgesamt 210)
🔹 Lade Seite mit Offset=150 …
✅ 14 Organisationen gefunden (bisher insgesamt 224)
🔹 Lade Seite mit Offset=160 …
✅ 14 Organisationen gefunden (bisher insgesamt 238)
🔹 Lade Seite mit Offset=170 …
✅ 14 Organisationen gefunden (bisher insgesamt 252)
🔹 Lade Seite mit Offset=180 …
✅ 14 Organisationen gefunden (bisher insgesamt 266)
🔹 Lade Seite mit Offset=190 …
✅ 14 Organisationen gefunden (bisher insgesamt 280)
🔹 Lade Seite mit Offset=200 …
✅ 14 Organisationen gefunden (bisher insgesamt 294)
🔹 Lade Seite mit Offset=210 …
✅ 14 Organisationen gefunden (bisher insgesamt 308)
🔹 Lade Seite mit Offset=220 …
✅ 14 Organisationen gefunden (bisher insgesamt 322)
🔹 Lade Seite mit Offset=230 …
✅ 14 Organisationen gefunden (bisher insgesamt 336)
🔹 Lade Seite mit Offset=240 …
✅ 14 Organisationen gefunden (bisher insgesamt 350)
🔹 Lade Seite mit Offset=250 …
✅ 14 Organisationen gefunden (bisher insgesamt 364)
🔹 Lade Seite mit Offset=260 …
✅ 14 Organisationen gefunden (bisher insgesamt 378)
🔹 Lade Seite mit Offset=270 …
✅ 14 Organisationen gefunden (bisher insgesamt 392)
🔹 Lade Seite mit Offset=280 …
✅ 14 Organisationen gefunden (bisher insgesamt 406)
🔹 Lade Seite mit Offset=290 …
✅ 14 Organisationen gefunden (bisher insgesamt 420)
🔹 Lade Seite mit Offset=300 …
✅ 14 Organisationen gefunden (bisher insgesamt 434)
🔹 Lade Seite mit Offset=310 …
✅ 14 Organisationen gefunden (bisher insgesamt 448)
🔹 Lade Seite mit Offset=320 …
✅ 14 Organisationen gefunden (bisher insgesamt 462)
🔹 Lade Seite mit Offset=330 …
✅ 14 Organisationen gefunden (bisher insgesamt 476)
🔹 Lade Seite mit Offset=340 …
✅ 14 Organisationen gefunden (bisher insgesamt 490)
🔹 Lade Seite mit Offset=350 …
✅ 14 Organisationen gefunden (bisher insgesamt 504)
🔹 Lade Seite mit Offset=360 …
✅ 14 Organisationen gefunden (bisher insgesamt 518)
🔹 Lade Seite mit Offset=370 …
✅ 14 Organisationen gefunden (bisher insgesamt 532)
🔹 Lade Seite mit Offset=380 …
✅ 14 Organisationen gefunden (bisher insgesamt 546)
🔹 Lade Seite mit Offset=390 …
✅ 14 Organisationen gefunden (bisher insgesamt 560)
🔹 Lade Seite mit Offset=400 …
✅ 14 Organisationen gefunden (bisher insgesamt 574)
🔹 Lade Seite mit Offset=410 …
✅ 14 Organisationen gefunden (bisher insgesamt 588)
🔹 Lade Seite mit Offset=420 …
✅ 14 Organisationen gefunden (bisher insgesamt 602)
🔹 Lade Seite mit Offset=430 …
✅ 14 Organisationen gefunden (bisher insgesamt 616)
🔹 Lade Seite mit Offset=440 …
✅ 14 Organisationen gefunden (bisher insgesamt 630)
🔹 Lade Seite mit Offset=450 …
✅ 14 Organisationen gefunden (bisher insgesamt 644)
🔹 Lade Seite mit Offset=460 …
✅ 14 Organisationen gefunden (bisher insgesamt 658)
🔹 Lade Seite mit Offset=470 …
✅ 14 Organisationen gefunden (bisher insgesamt 672)
🔹 Lade Seite mit Offset=480 …
✅ 14 Organisationen gefunden (bisher insgesamt 686)
🔹 Lade Seite mit Offset=490 …
✅ 14 Organisationen gefunden (bisher insgesamt 700)
🔹 Lade Seite mit Offset=500 …
✅ 14 Organisationen gefunden (bisher insgesamt 714)
🔹 Lade Seite mit Offset=510 …
✅ 14 Organisationen gefunden (bisher insgesamt 728)
🔹 Lade Seite mit Offset=520 …
✅ 14 Organisationen gefunden (bisher insgesamt 742)
🔹 Lade Seite mit Offset=530 …
✅ 14 Organisationen gefunden (bisher insgesamt 756)
🔹 Lade Seite mit Offset=540 …
✅ 14 Organisationen gefunden (bisher insgesamt 770)
🔹 Lade Seite mit Offset=550 …
✅ 14 Organisationen gefunden (bisher insgesamt 784)
🔹 Lade Seite mit Offset=560 …
✅ 14 Organisationen gefunden (bisher insgesamt 798)
🔹 Lade Seite mit Offset=570 …
✅ 14 Organisationen gefunden (bisher insgesamt 812)
🔹 Lade Seite mit Offset=580 …
✅ 14 Organisationen gefunden (bisher insgesamt 826)
🔹 Lade Seite mit Offset=590 …
✅ 14 Organisationen gefunden (bisher insgesamt 840)
🔹 Lade Seite mit Offset=600 …
✅ 14 Organisationen gefunden (bisher insgesamt 854)
🔹 Lade Seite mit Offset=610 …
✅ 14 Organisationen gefunden (bisher insgesamt 868)
🔹 Lade Seite mit Offset=620 …
✅ 14 Organisationen gefunden (bisher insgesamt 882)
🔹 Lade Seite mit Offset=630 …
✅ 14 Organisationen gefunden (bisher insgesamt 896)
🔹 Lade Seite mit Offset=640 …
✅ 14 Organisationen gefunden (bisher insgesamt 910)
🔹 Lade Seite mit Offset=650 …
✅ 14 Organisationen gefunden (bisher insgesamt 924)
🔹 Lade Seite mit Offset=660 …
✅ 14 Organisationen gefunden (bisher insgesamt 938)
🔹 Lade Seite mit Offset=670 …
✅ 14 Organisationen gefunden (bisher insgesamt 952)
🔹 Lade Seite mit Offset=680 …
✅ 14 Organisationen gefunden (bisher insgesamt 966)
🔹 Lade Seite mit Offset=690 …
✅ 14 Organisationen gefunden (bisher insgesamt 980)
🔹 Lade Seite mit Offset=700 …
✅ 14 Organisationen gefunden (bisher insgesamt 994)
🔹 Lade Seite mit Offset=710 …
✅ 14 Organisationen gefunden (bisher insgesamt 1008)
🔹 Lade Seite mit Offset=720 …
✅ 14 Organisationen gefunden (bisher insgesamt 1022)
🔹 Lade Seite mit Offset=730 …
✅ 14 Organisationen gefunden (bisher insgesamt 1036)
🔹 Lade Seite mit Offset=740 …
✅ 14 Organisationen gefunden (bisher insgesamt 1050)
🔹 Lade Seite mit Offset=750 …
✅ 14 Organisationen gefunden (bisher insgesamt 1064)
🔹 Lade Seite mit Offset=760 …
✅ 14 Organisationen gefunden (bisher insgesamt 1078)
🔹 Lade Seite mit Offset=770 …
✅ 14 Organisationen gefunden (bisher insgesamt 1092)
🔹 Lade Seite mit Offset=780 …
✅ 14 Organisationen gefunden (bisher insgesamt 1106)
🔹 Lade Seite mit Offset=790 …
✅ 14 Organisationen gefunden (bisher insgesamt 1120)
🔹 Lade Seite mit Offset=800 …
✅ 14 Organisationen gefunden (bisher insgesamt 1134)
🔹 Lade Seite mit Offset=810 …
✅ 13 Organisationen gefunden (bisher insgesamt 1147)

🎉 Fertig! Insgesamt 1147 Organisationen gesammelt.

                                                 Name
0   Hier finden Sie eine Übersicht aller Mitglieds...
1                                    #BIKEYGEES e. V.
2   ABC Blindenwohnstätte in Weißensee gemeinnützi...
3   ABH - Anlauf- und Beratungsstelle für Menschen...
4                                       ABqueer e. V.
5                     ABSV Service gemeinnützige GmbH
6                 abw - arbeit, bildung, wohnen e. V.
7   abw - gemeinnützige Gesellschaft für Arbeit, B...
8   ADV - Rehabilitation und Integration gemeinnüt...
9                         Advent Wohlfahrtswerk e. V.
10  Advent-Wohlfahrtswerk Seniorenheim Steglitz gGmbH
11                                 Notwendige Cookies
12                                          Statistik
13                                    Externe Inhalte
14  Hier finden Sie eine Übersicht aller Mitglieds...
15                                 afro-talents e. V.
16  ajb gmbh Gemeinnützige Gesellschaft für Jugend...
17  AJC GmbH Gemeinnützige Gesellschaft für Jugend...
18           Aktion 70 - Jugendhilfe im Verbund e. V.
19               Aktion Courage e. V. - SOS Rassismus

Gesamtzahl der Organisationen: 1147

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep

BASE_URL = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen"
results = []

# Begriffe, die wir NICHT im Ergebnis haben wollen
blacklist = [
    "Hier finden Sie eine Übersicht aller Mitgliedsorganisationen des Paritätischen Berlin. Einzelne Organisationen finden Sie über die alphabetische Reihenfolge oder über Suchbegriffe.",
    "Notwendige Cookies",
    "Statistik",
    "Externe Inhalte"
]

for offset in range(0, 820, 10):
    url = f"{BASE_URL}?tx_lfmembers_list[offset]={offset}"
    print(f"🔹 Lade Seite mit Offset={offset} …")

    r = requests.get(url)
    if r.status_code != 200:
        print(f"⚠️ Fehler bei {url}: Status {r.status_code}")
        continue

    soup = BeautifulSoup(r.text, "html.parser")
    orgs = soup.find_all("h3")

    if not orgs:
        print(f"⚠️ Keine Organisationen auf Seite {offset} gefunden")
        continue

    for org in orgs:
        name = org.get_text(strip=True)

        # Falls einer der Blacklist-Begriffe vorkommt → überspringen
        if any(bad in name for bad in blacklist):
            continue

        results.append({"Name": name})

    print(f"✅ {len(orgs)} Organisationen (bisher insgesamt {len(results)})")
    sleep(1)

print(f"\n🎉 Fertig! Insgesamt {len(results)} Organisationen gesammelt.")

# Ergebnisse als DataFrame anzeigen
df = pd.DataFrame(results)
display(df.head(20))
print(f"Gesamtzahl der Organisationen: {len(df)}")

🔹 Lade Seite mit Offset=0 …
✅ 14 Organisationen (bisher insgesamt 10)
🔹 Lade Seite mit Offset=10 …
✅ 14 Organisationen (bisher insgesamt 20)
🔹 Lade Seite mit Offset=20 …
✅ 14 Organisationen (bisher insgesamt 30)
🔹 Lade Seite mit Offset=30 …
✅ 14 Organisationen (bisher insgesamt 40)
🔹 Lade Seite mit Offset=40 …
✅ 14 Organisationen (bisher insgesamt 50)
🔹 Lade Seite mit Offset=50 …
✅ 14 Organisationen (bisher insgesamt 60)
🔹 Lade Seite mit Offset=60 …
✅ 14 Organisationen (bisher insgesamt 70)
🔹 Lade Seite mit Offset=70 …
✅ 14 Organisationen (bisher insgesamt 80)
🔹 Lade Seite mit Offset=80 …
✅ 14 Organisationen (bisher insgesamt 90)
🔹 Lade Seite mit Offset=90 …
✅ 14 Organisationen (bisher insgesamt 100)
🔹 Lade Seite mit Offset=100 …
✅ 14 Organisationen (bisher insgesamt 110)
🔹 Lade Seite mit Offset=110 …
✅ 14 Organisationen (bisher insgesamt 120)
🔹 Lade Seite mit Offset=120 …
✅ 14 Organisationen (bisher insgesamt 130)
🔹 Lade Seite mit Offset=130 …
✅ 14 Organisationen (bisher insgesamt 140)
🔹 Lade Seite mit Offset=140 …
✅ 14 Organisationen (bisher insgesamt 150)
🔹 Lade Seite mit Offset=150 …
✅ 14 Organisationen (bisher insgesamt 160)
🔹 Lade Seite mit Offset=160 …
✅ 14 Organisationen (bisher insgesamt 170)
🔹 Lade Seite mit Offset=170 …
✅ 14 Organisationen (bisher insgesamt 180)
🔹 Lade Seite mit Offset=180 …
✅ 14 Organisationen (bisher insgesamt 190)
🔹 Lade Seite mit Offset=190 …
✅ 14 Organisationen (bisher insgesamt 200)
🔹 Lade Seite mit Offset=200 …
✅ 14 Organisationen (bisher insgesamt 210)
🔹 Lade Seite mit Offset=210 …
✅ 14 Organisationen (bisher insgesamt 220)
🔹 Lade Seite mit Offset=220 …
✅ 14 Organisationen (bisher insgesamt 230)
🔹 Lade Seite mit Offset=230 …
✅ 14 Organisationen (bisher insgesamt 240)
🔹 Lade Seite mit Offset=240 …
✅ 14 Organisationen (bisher insgesamt 250)
🔹 Lade Seite mit Offset=250 …
✅ 14 Organisationen (bisher insgesamt 260)
🔹 Lade Seite mit Offset=260 …
✅ 14 Organisationen (bisher insgesamt 270)
🔹 Lade Seite mit Offset=270 …
✅ 14 Organisationen (bisher insgesamt 280)
🔹 Lade Seite mit Offset=280 …
✅ 14 Organisationen (bisher insgesamt 290)
🔹 Lade Seite mit Offset=290 …
✅ 14 Organisationen (bisher insgesamt 300)
🔹 Lade Seite mit Offset=300 …
✅ 14 Organisationen (bisher insgesamt 310)
🔹 Lade Seite mit Offset=310 …
✅ 14 Organisationen (bisher insgesamt 320)
🔹 Lade Seite mit Offset=320 …
✅ 14 Organisationen (bisher insgesamt 330)
🔹 Lade Seite mit Offset=330 …
✅ 14 Organisationen (bisher insgesamt 340)
🔹 Lade Seite mit Offset=340 …
✅ 14 Organisationen (bisher insgesamt 350)
🔹 Lade Seite mit Offset=350 …
✅ 14 Organisationen (bisher insgesamt 360)
🔹 Lade Seite mit Offset=360 …
✅ 14 Organisationen (bisher insgesamt 370)
🔹 Lade Seite mit Offset=370 …
✅ 14 Organisationen (bisher insgesamt 380)
🔹 Lade Seite mit Offset=380 …
✅ 14 Organisationen (bisher insgesamt 390)
🔹 Lade Seite mit Offset=390 …
✅ 14 Organisationen (bisher insgesamt 400)
🔹 Lade Seite mit Offset=400 …
✅ 14 Organisationen (bisher insgesamt 410)
🔹 Lade Seite mit Offset=410 …
✅ 14 Organisationen (bisher insgesamt 420)
🔹 Lade Seite mit Offset=420 …
✅ 14 Organisationen (bisher insgesamt 430)
🔹 Lade Seite mit Offset=430 …
✅ 14 Organisationen (bisher insgesamt 440)
🔹 Lade Seite mit Offset=440 …
✅ 14 Organisationen (bisher insgesamt 450)
🔹 Lade Seite mit Offset=450 …
✅ 14 Organisationen (bisher insgesamt 460)
🔹 Lade Seite mit Offset=460 …
✅ 14 Organisationen (bisher insgesamt 470)
🔹 Lade Seite mit Offset=470 …
✅ 14 Organisationen (bisher insgesamt 480)
🔹 Lade Seite mit Offset=480 …
✅ 14 Organisationen (bisher insgesamt 490)
🔹 Lade Seite mit Offset=490 …
✅ 14 Organisationen (bisher insgesamt 500)
🔹 Lade Seite mit Offset=500 …
✅ 14 Organisationen (bisher insgesamt 510)
🔹 Lade Seite mit Offset=510 …
✅ 14 Organisationen (bisher insgesamt 520)
🔹 Lade Seite mit Offset=520 …
✅ 14 Organisationen (bisher insgesamt 530)
🔹 Lade Seite mit Offset=530 …
✅ 14 Organisationen (bisher insgesamt 540)
🔹 Lade Seite mit Offset=540 …
✅ 14 Organisationen (bisher insgesamt 550)
🔹 Lade Seite mit Offset=550 …
✅ 14 Organisationen (bisher insgesamt 560)
🔹 Lade Seite mit Offset=560 …
✅ 14 Organisationen (bisher insgesamt 570)
🔹 Lade Seite mit Offset=570 …
✅ 14 Organisationen (bisher insgesamt 580)
🔹 Lade Seite mit Offset=580 …
✅ 14 Organisationen (bisher insgesamt 590)
🔹 Lade Seite mit Offset=590 …
✅ 14 Organisationen (bisher insgesamt 600)
🔹 Lade Seite mit Offset=600 …
✅ 14 Organisationen (bisher insgesamt 610)
🔹 Lade Seite mit Offset=610 …
✅ 14 Organisationen (bisher insgesamt 620)
🔹 Lade Seite mit Offset=620 …
✅ 14 Organisationen (bisher insgesamt 630)
🔹 Lade Seite mit Offset=630 …
✅ 14 Organisationen (bisher insgesamt 640)
🔹 Lade Seite mit Offset=640 …
✅ 14 Organisationen (bisher insgesamt 650)
🔹 Lade Seite mit Offset=650 …
✅ 14 Organisationen (bisher insgesamt 660)
🔹 Lade Seite mit Offset=660 …
✅ 14 Organisationen (bisher insgesamt 670)
🔹 Lade Seite mit Offset=670 …
✅ 14 Organisationen (bisher insgesamt 680)
🔹 Lade Seite mit Offset=680 …
✅ 14 Organisationen (bisher insgesamt 690)
🔹 Lade Seite mit Offset=690 …
✅ 14 Organisationen (bisher insgesamt 700)
🔹 Lade Seite mit Offset=700 …
✅ 14 Organisationen (bisher insgesamt 710)
🔹 Lade Seite mit Offset=710 …
✅ 14 Organisationen (bisher insgesamt 720)
🔹 Lade Seite mit Offset=720 …
✅ 14 Organisationen (bisher insgesamt 730)
🔹 Lade Seite mit Offset=730 …
✅ 14 Organisationen (bisher insgesamt 740)
🔹 Lade Seite mit Offset=740 …
✅ 14 Organisationen (bisher insgesamt 750)
🔹 Lade Seite mit Offset=750 …
✅ 14 Organisationen (bisher insgesamt 760)
🔹 Lade Seite mit Offset=760 …
✅ 14 Organisationen (bisher insgesamt 770)
🔹 Lade Seite mit Offset=770 …
✅ 14 Organisationen (bisher insgesamt 780)
🔹 Lade Seite mit Offset=780 …
✅ 14 Organisationen (bisher insgesamt 790)
🔹 Lade Seite mit Offset=790 …
✅ 14 Organisationen (bisher insgesamt 800)
🔹 Lade Seite mit Offset=800 …
✅ 14 Organisationen (bisher insgesamt 810)
🔹 Lade Seite mit Offset=810 …
✅ 13 Organisationen (bisher insgesamt 819)

🎉 Fertig! Insgesamt 819 Organisationen gesammelt.

                                                 Name
0                                    #BIKEYGEES e. V.
1   ABC Blindenwohnstätte in Weißensee gemeinnützi...
2   ABH - Anlauf- und Beratungsstelle für Menschen...
3                                       ABqueer e. V.
4                     ABSV Service gemeinnützige GmbH
5                 abw - arbeit, bildung, wohnen e. V.
6   abw - gemeinnützige Gesellschaft für Arbeit, B...
7   ADV - Rehabilitation und Integration gemeinnüt...
8                         Advent Wohlfahrtswerk e. V.
9   Advent-Wohlfahrtswerk Seniorenheim Steglitz gGmbH
10                                 afro-talents e. V.
11  ajb gmbh Gemeinnützige Gesellschaft für Jugend...
12  AJC GmbH Gemeinnützige Gesellschaft für Jugend...
13           Aktion 70 - Jugendhilfe im Verbund e. V.
14               Aktion Courage e. V. - SOS Rassismus
15                  Aktion für Flüchtlingshilfe e. V.
16        aktion weitblick - betreutes wohnen - gGmbH
17  aktion weitblick e. V. (Interessengemeinschaft...
18                        Albatros - Lebensnetz gGmbH
19                                     Albatros e. V.

Gesamtzahl der Organisationen: 819

In [11]:
# Excel-Export der bisherigen Ergebnisse
SAVE_PATH = "/Users/raffaelruppert/Desktop/SocialMap_Dashboard/data/paritaet_mitgliedsorgas_names.xlsx"
df.to_excel(SAVE_PATH, index=False)
print(f"✅ Datei gespeichert unter: {SAVE_PATH}")

✅ Datei gespeichert unter: /Users/raffaelruppert/Desktop/SocialMap_Dashboard/data/paritaet_mitgliedsorgas_names.xlsx

In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep

BASE_URL = "https://www.paritaet-berlin.de/mitglieder/unsere-mitgliedsorganisationen"
results = []

blacklist = [
    "Hier finden Sie eine Übersicht aller Mitgliedsorganisationen des Paritätischen Berlin. Einzelne Organisationen finden Sie über die alphabetische Reihenfolge oder über Suchbegriffe.",
    "Notwendige Cookies",
    "Statistik",
    "Externe Inhalte"
]

for offset in range(0, 820, 10):
    url = f"{BASE_URL}?tx_lfmembers_list[offset]={offset}"
    print(f"🔹 Lade Seite mit Offset={offset} …")

    r = requests.get(url)
    if r.status_code != 200:
        print(f"⚠️ Fehler bei {url}: Status {r.status_code}")
        continue

    soup = BeautifulSoup(r.text, "html.parser")

    # Jeder Organisationseintrag steckt in div.members__item
    items = soup.find_all("div", class_="members__item")
    if not items:
        print(f"⚠️ Keine Organisationen auf Seite {offset} gefunden")
        continue

    for item in items:
        name_tag = item.find("h3")
        link_tag = item.find("a")

        if not name_tag or not link_tag:
            continue

        name = name_tag.get_text(strip=True)
        link = link_tag.get("href")

        if any(bad in name for bad in blacklist):
            continue

        if link and not link.startswith("http"):
            link = "https://www.paritaet-berlin.de" + link

        results.append({"Name": name, "Link": link})

    print(f"✅ {len(items)} Organisationen (bisher insgesamt {len(results)})")
    sleep(1)

print(f"\n🎉 Fertig! Insgesamt {len(results)} Organisationen gesammelt.")

df_links = pd.DataFrame(results)
display(df_links.head(20))
print(f"Gesamtzahl der Organisationen: {len(df_links)}")

🔹 Lade Seite mit Offset=0 …
⚠️ Keine Organisationen auf Seite 0 gefunden
🔹 Lade Seite mit Offset=10 …
⚠️ Keine Organisationen auf Seite 10 gefunden
🔹 Lade Seite mit Offset=20 …
⚠️ Keine Organisationen auf Seite 20 gefunden
🔹 Lade Seite mit Offset=30 …
⚠️ Keine Organisationen auf Seite 30 gefunden
🔹 Lade Seite mit Offset=40 …
⚠️ Keine Organisationen auf Seite 40 gefunden
🔹 Lade Seite mit Offset=50 …

KeyboardInterrupt: